import {useEffect,useState} from 'react';
import {ArrowRight,Check,ChevronRight,Clock,KeyRound,MapPin,PackageCheck,ScanSearch,ShieldCheck,Sparkles,Truck,Upload,UserCheck,X} from 'lucide-react';
import {DemoApp} from './DemoApp';

const locations=['Hotel rooms','Gaming floor','Restaurants','Event spaces','Parking & valet','Retail'];
const safeguards=['Cash & gaming tickets','IDs & passports','Medication','Electronics','Sensitive items','Weapons'];
const journey=[{n:'01',icon:Upload,title:'Report it',copy:'A two-minute, no-account report captures where, when, photos and the details only the owner would know.'},{n:'02',icon:ScanSearch,title:'Match it',copy:'Smart suggestions connect guest reports with staff-found inventory across the entire resort campus.'},{n:'03',icon:PackageCheck,title:'Bring it home',copy:'Release through verified pickup—or let the guest choose transparent, tracked shipping.'}];

export function App(){
 const [modal,setModal]=useState<'lost'|'demo'|null>(null); const [status,setStatus]=useState(0); const [demoRole,setDemoRole]=useState<'guest'|'management'|null>(null);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>e.key==='Escape'&&setModal(null);addEventListener('keydown',onKey);return()=>removeEventListener('keydown',onKey)},[]);
 if(demoRole)return <DemoApp initialRole={demoRole} close={()=>setDemoRole(null)}/>;
 return <main>
  <nav><a className="brand" href="#top"><span><Sparkles size={18}/></span>Found Again<small>for resorts</small></a><div className="navlinks"><a href="#journey">How it works</a><a href="#platform">Platform</a><a href="#trust">Trust</a></div><button className="navcta" onClick={()=>setDemoRole('management')}>Launch live demo <ArrowRight size={15}/></button></nav>
  <header id="top" className="hero"><div className="heroImage"/><div className="glow"/><div className="heroCopy"><p className="eyebrow"><span/> Lost happens. Happy endings should, too.</p><h1>Every lost item deserves a way <em>home.</em></h1><p className="lede">One beautifully simple journey from “I left it behind” to “I’ve got it back”—built for the pace and complexity of modern resorts.</p><div className="actions"><button className="primary" onClick={()=>setDemoRole('guest')}>Try the guest demo <ArrowRight/></button><button className="secondary" onClick={()=>setDemoRole('management')}>Open management demo</button></div><div className="promise"><span><Clock/> Report in minutes</span><span><ShieldCheck/> Track every step</span><span><Truck/> Pickup or ship</span></div></div><a className="scroll" href="#journey">Follow the journey <span>↓</span></a></header>
  <section className="ticker" aria-label="Supported resort locations"><div>{[...locations,...locations].map((x,i)=><span key={i}>{x}<b>✦</b></span>)}</div></section>
  <section id="journey" className="section journey"><div className="sectionIntro"><p className="kicker">From missing to reunited</p><h2>Three steps. Zero mystery.</h2><p>Guests stay informed while your team gets one clear, accountable workflow.</p></div><div className="journeyGrid">{journey.map(({icon:Icon,...x},i)=><article key={x.n}><div className="stepTop"><span>{x.n}</span><Icon/></div><h3>{x.title}</h3><p>{x.copy}</p>{i<2&&<ChevronRight className="stepArrow"/>}</article>)}</div></section>
  <section id="platform" className="section split"><div className="guestPane"><p className="kicker">The guest experience</p><h2>Reassurance starts before the item is found.</h2><p className="sub">No account. No phone-tree marathon. Just a clear report and a private tracking link.</p><ul>{['Property, location and date details','Photos and proof-of-ownership clues','Proactive email and text updates','Verified pickup or tracked shipping'].map(x=><li key={x}><Check/> {x}</li>)}</ul><button className="textButton" onClick={()=>setModal('lost')}>Try the guest journey <ArrowRight/></button></div><StatusDemo status={status} setStatus={setStatus}/></section>
  <section className="section ops"><div className="opsVisual"><div className="phone"><div className="phoneTop"><span>9:41</span><b>Found item</b></div><div className="photo"><KeyRound/><span>Photo added</span></div><label>Found at</label><div className="field"><MapPin/> North Tower · Room 1428</div><label>Secure storage</label><div className="field"><ShieldCheck/> Vault B · Bin 17</div><button>Log item <ArrowRight/></button></div><div className="match"><span>Possible match</span><strong>92%</strong><p>Black key fob · North Tower</p></div></div><div className="opsCopy"><p className="kicker">One system for every team</p><h2>Found at 10:42. Accounted for at 10:43.</h2><p>Give Security, EVS, Hotel, Slots, Food & Beverage and Valet a shared source of truth—without giving everyone access to everything.</p><div className="featureGrid">{[['Mobile intake','Photos, exact location and storage bin in seconds.'],['Smart matching','Cross-campus suggestions as new reports arrive.'],['Investigations','Assign owners, tasks and follow-ups by department.'],['Chain of custody','Every handoff, move, release and disposal recorded.'],['Policy engine','Retention and special handling by item category.'],['Useful analytics','Recovery, response and aging trends—not vanity charts.']].map(([a,b])=><div key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
  <section className="section special"><div className="sectionIntro"><p className="kicker">Built for resort reality</p><h2>Not everything belongs in the same lost-and-found bin.</h2></div><div className="chips">{safeguards.map((x,i)=><span key={x} style={{'--i':i} as React.CSSProperties}>{x}</span>)}</div><p className="specialCopy">Category-aware workflows route high-risk items to the right team, apply the right retention rules, and preserve the right evidence—automatically.</p></section>
  <section className="section returns"><div><p className="kicker">Return, their way</p><h2>The last mile should feel as polished as the stay.</h2></div><div className="returnCards"><article><UserCheck/><h3>Verified pickup</h3><p>Secure QR and ownership check at the property.</p><span>Ready when they are</span></article><article><UserCheck/><h3>Authorized pickup</h3><p>Guest designates someone else with a verified handoff.</p><span>No awkward phone calls</span></article><article><Truck/><h3>Tracked shipping</h3><p>Clear carrier choices, honest pricing and live tracking.</p><span>No surprise markup</span></article></div></section>
  <section id="trust" className="section trust"><div className="trustMark"><ShieldCheck/><span>Private by design</span></div><div><p className="kicker">Trust is part of the return</p><h2>Inventory stays private. Accountability stays visible.</h2><div className="trustGrid">{['Role-based access','Protected guest information','Proof-of-ownership questions','Complete audit history'].map(x=><span key={x}><Check/> {x}</span>)}</div></div></section>
  <section className="final"><Sparkles/><p>Turn a stressful moment into</p><h2>a reason to come back.</h2><button className="primary" onClick={()=>setDemoRole('management')}>Launch the connected demo <ArrowRight/></button></section>
  <footer><a className="brand" href="#top"><span><Sparkles size={18}/></span>Found Again</a><p>Lost & found, thoughtfully rebuilt for resort hospitality.</p><span>Concept by CloudKicker · 2026</span></footer>
  {modal&&<Modal type={modal} close={()=>setModal(null)}/>} 
 </main>
}

function StatusDemo({status,setStatus}:{status:number,setStatus:(n:number)=>void}){const states=[['Report received','Your report is safely with the resort team.'],['Possible match','Good news—we’re verifying an item now.'],['Ready to return','Choose pickup or tracked shipping.']];return <div className="statusDemo"><div className="demoHead"><span>Private tracking</span><b>FA-84219</b></div><div className="item"><div>🕶️</div><span>Round black sunglasses<small>Reported today · North Tower</small></span></div><div className="timeline">{states.map((s,i)=><button key={s[0]} onClick={()=>setStatus(i)} className={i<=status?'active':''}><i>{i<status?<Check/>:i+1}</i><span><b>{s[0]}</b><small>{s[1]}</small></span></button>)}</div><button className="advance" onClick={()=>setStatus((status+1)%3)}>{status===2?'Replay the journey':'See the next update'} <ArrowRight/></button></div>}

function Modal({type,close}:{type:'lost'|'demo',close:()=>void}){return <div className="backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal" role="dialog" aria-modal="true"><button className="close" onClick={close} aria-label="Close"><X/></button><p className="kicker">{type==='lost'?'Guest report preview':'Property demo'}</p><h2>{type==='lost'?'Let’s retrace your steps.':'Let’s make lost & found a guest-service win.'}</h2><p>{type==='lost'?'The working app will begin with property, location and time—then collect photos and private identifying details. No account required.':'This concept is ready to tailor for a resort campus, departments and operating policies.'}</p><div className="fakeForm">{type==='lost'?<><label>Where did you last have it?</label><button><MapPin/> Choose resort location <ChevronRight/></button><label>What went missing?</label><button><Sparkles/> Tell us about the item <ChevronRight/></button></>:<><label>Your work email</label><input placeholder="name@resort.com" type="email"/><button className="primary">Request a walkthrough <ArrowRight/></button></>}</div><small>Interactive prototype · No information is submitted</small></div></div>}
